### ISSUE TITLE
Specifing a custom N should not remove the defaults but impl it for N in addition to defaults

### ISSUE THREAD

**Issue by Boscop** [est31/serde-big-array#4]
Specifing a custom N should not remove the defaults but impl it for N in addition to defaults.

E.g. when I do `big_array! { BigArray; 823, }`, it won't work for all my other arrays that have sizes that are supported by `big_array! { BigArray; }`
I know I can define both, with different names, but I'd prefer to have the same name, because I have a lot of non-standard sizes and I think the goal of this crate is to make it as seamless as for Vecs.

**Comment by est31** [comment]
I think I made the array override the entire list so that people have full flexibility. Also to allow expansion of the builtin list in the future without breaking changes. But as I haven't expanded the list I suppose we can add such a feature.

To avoid breaking changes we shouldn't override the default mode but add new syntax. e.g. a plus sign as separator.

**Comment by Boscop** [comment]
Yea, that would be great :)
