### ISSUE TITLE
Omit trailing comma

### ISSUE THREAD

**Issue by daniel5151** [est31/serde-big-array#9]
Nice crate!

It'd be nice if it was possible to omit the trailing comma when specifying additional array sizes. i.e:

```rust
big_array! {
    BigArray;
    +42, 300, 1234, 99999, // <--- remove `,`
}
```

It's particularly out of place when specifying only a single additional array size:

```rust
big_array! {
    BigArray;
    +42, // ?
}
```

Cheers :)

**Comment by est31** [comment]
Trailing commas are a good idea for VCS tools because they allow you to add new items on new lines without the line before appearing as being edited. Of course if your preference is different that's a use case I want to support. The ? macro operator became stable in 1.32.0 on the 2018 edition. Maybe we can release 0.3.0 with the change. PRs welcome.
